using StudentPerfomance.Application.EntitySchemas.Schemas.EducationDirections;

namespace StudentPerfomance.Api.Requests.EducationDirectionRequests;

public record UpdateEducationDirectionRequest(EducationDirectionSchema OldSchema, EducationDirectionSchema NewSchema);
